### ISSUE TITLE
Fastq files

### ISSUE THREAD

**Issue by eravza** [kjgaulton/pipelines#10]
Hi, I was wondering how I can access the fastq files of snATAC-seq lung data. In GEO website of samples, it says that raw data are available in SRA but I couldn't see any SRA accession id. I also checked the website, https://www.lungepigenome.org/, there are only matrix, barcodes and regions information available.

Thank you in advance.

**Comment by joshchiou** [comment]
Hi, thank you for your interest. Please contact the corresponding authors by email. They will be able to answer your question.

a5wang[at]health.ucsd.edu
kgaulton[at]health.ucsd.edu
spreissl[at]health.ucsd.edu
xinsun[at]health.ucsd.edu
