### ISSUE TITLE
Visualization tools

### ISSUE THREAD

**Issue by wgmao** [kjgaulton/pipelines#11]
Hi, I was wondering how the Figure 2a (https://doi.org/10.1038/s41586-021-03552-w) was generated. The annotation layer looks really nice. Thank you.

**Comment by joshchiou** [comment]
Hi there, I generated the UMAP plot in python and annotated the clusters using Adobe Illustrator.

**Comment by wgmao** [comment]
Thank you for your instant reply. I just thought there might be some automated ways to generate this impressive layout for celltype annotation or it had to be carefully arranged by hand. Thank you very much for the information.
